### ISSUE TITLE
tmux exits immediately after starting

### ISSUE THREAD

**Issue by richard-cryptodotcom** [haoxilu/dotfiles-local#9]
https://unix.stackexchange.com/questions/128190/tmux-exits-immediately-after-starting

https://superuser.com/questions/397076/tmux-exits-with-exited-on-mac-os-x

**Comment by richard-cryptodotcom** [comment]
The solution is to install reattach-to-user-namespace `brew install reattach-to-user-namespace`

**Comment by haoxilu** [comment]
done. https://github.com/haoxilu/dotfiles-local/commit/792f4e59c090c59fbbd2f514a458990de32d7a14
